import re
import os

with open("/Users/divyyadav/final_tool/controllertesting/src/pages/index.astro", "r") as f:
    content = f.read()

# Fix imports for subdirectory
content = content.replace("'../layouts/BaseLayout.astro'", "'../../layouts/BaseLayout.astro'")
content = content.replace("'../components/global/Header.astro'", "'../../components/global/Header.astro'")
content = content.replace("'../components/global/Footer.astro'", "'../../components/global/Footer.astro'")
content = content.replace("'../components/global/ControllerHero.astro'", "'../../components/global/ControllerHero.astro'")

# Add useTranslations import
content = content.replace(
    "import ControllerHero from '../../components/global/ControllerHero.astro';",
    "import ControllerHero from '../../components/global/ControllerHero.astro';\nimport { useTranslations } from '../../i18n/utils';"
)

langs = ['es', 'de', 'fr', 'ja']

translations = {
    'es': {
        'Controller Test Online | Free Gamepad Tester': 'Prueba de Mando Online | Analizador de Gamepad Gratis',
        'Run a free controller test online for PS5, PS4, Xbox, Switch, and PC. Use a gamepad tester to check drift, buttons, triggers, polling rate, and rumble.': 'Haz una prueba gratis de mando online para PS5, PS4, Xbox, Switch y PC. Usa un analizador para comprobar drift, botones, gatillos, polling rate y vibración.',
        'Controller test / precision diagnostics': 'Prueba de mando / diagnósticos de precisión',
        'Browser / ready': 'Navegador / listo',
        'Diagnose stick drift': 'Diagnostica el stick drift',
        'before you lose.': 'antes de perder.',
        'Test your controller, mouse, and keyboard instantly. Catch drift, latency, and button failures before your warranty expires. Experience that you have never felt before.': 'Prueba tu mando, ratón y teclado al instante. Detecta drift, latencia y fallos en los botones antes de que expire tu garantía. Una experiencia que nunca antes habías sentido.',
        'Test your controller': 'Prueba tu mando',
        'Check stick drift': 'Comprueba el stick drift',
        'hardware telemetry samples measured': 'muestras de telemetría de hardware medidas',
        'Works with': 'Funciona con',
        'Live hardware telemetry': 'Telemetría de hardware en vivo',
        'samples': 'muestras',
        'drift &amp; circularity measurements from real controller tests': 'mediciones de drift y circularidad de pruebas reales de mandos',
        '29 tools. One controller.': '29 herramientas. Un mando.',
        '<br />Every test you need.': '<br />Todas las pruebas que necesitas.',
        'Flagship': 'Destacado',
        'Controller Health Score': 'Puntuación de Salud del Mando',
        'The only 0-100 score that measures drift, buttons, triggers, polling rate,': 'La única puntuación de 0-100 que mide drift, botones, gatillos, polling rate,',
        'and circularity in a single diagnostic. Get your grade: A+ to F.': 'y circularidad en un solo diagnóstico. Obtén tu calificación: A+ a F.',
        'Get your score': 'Obtén tu puntuación',
        'View all 29 controller tests': 'Ver las 29 pruebas de mando',
        'Mouse tests': 'Pruebas de ratón',
        'Keyboard tests': 'Pruebas de teclado',
        'Full-Setup Testing': 'Pruebas del Setup Completo',
        'Your mouse and keyboard get the same treatment.': 'Tu ratón y teclado reciben el mismo trato.',
        'CPS speed, true DPI, 8K polling, click latency, double-click faults, scroll-wheel health —': 'Velocidad CPS, DPI real, polling 8K, latencia de clic, fallos de doble clic, salud de la rueda de desplazamiento —',
        '7 mouse tools. Plus a mechanical keyboard sandbox with NKRO matrix verification.': '7 herramientas de ratón. Además de un entorno de pruebas para teclados mecánicos con verificación de matriz NKRO.',
        'Keyboard Sandbox': 'Sandbox de Teclado',
        'One platform.': 'Una plataforma.',
        '<br />Every answer.': '<br />Todas las respuestas.',
        'When your controller feels off, you currently visit 5-8 websites to': 'Cuando sientes algo mal en tu mando, actualmente visitas de 5 a 8 sitios web para',
        'solve one problem. We own the entire journey in one place.': 'resolver un solo problema. Nosotros tenemos todo el recorrido en un solo lugar.',
        'Start your journey': 'Comienza tu viaje',
        'Test your controller.': 'Prueba tu mando.',
        '<br />Then play with it.': '<br />Y luego juega con él.',
        '5 browser games built around your controller inputs. Earn XP points,': '5 juegos de navegador basados en tus inputs del mando. Gana puntos de XP,',
        'level up, build a daily streak. No gaming site has this.': 'sube de nivel y consigue una racha diaria. Ningún sitio de juegos tiene esto.',
        'Precision games': 'Juegos de precisión',
        'Reflex games': 'Juegos de reflejos',
        '2-Player games': 'Juegos de 2 jugadores',
        'Open Arcade': 'Abrir Arcade',
        'Earn while you play': 'Gana mientras juegas',
        'Test completion +50 pts': 'Prueba completada +50 pts',
        'Achievements unlock': 'Logros desbloqueados',
        'Leaderboard rank': 'Clasificación en la tabla',
        'Built different.<br />Not just another tester.': 'Creado diferente.<br />No solo otro probador.',
        'Every competitor is a single-page app with 5-30 indexed pages and zero content.': 'Todos los competidores son una sola página con 5-30 páginas indexadas y cero contenido.',
        'We are an 830+ page platform that owns the entire controller lifecycle.': 'Somos una plataforma de más de 830 páginas que abarca todo el ciclo de vida del mando.',
        'Other sites': 'Otros sitios',
        '5-30 indexed pages (SPA)': '5-30 páginas indexadas (SPA)',
        'Shows raw data, not answers': 'Muestra datos sin procesar, no respuestas',
        '2-4 minute sessions': 'Sesiones de 2-4 minutos',
        'Zero repair guides or content': 'Cero guías de reparación o contenido',
        'No games, no engagement loop': 'Sin juegos, sin ciclo de engagement',
        '830+ indexed pages (Astro SSG)': 'Más de 830 páginas indexadas (Astro SSG)',
        'Diagnoses, fixes, and optimizes': 'Diagnostica, arregla y optimiza',
        '8-15 minute sessions (games)': 'Sesiones de 8-15 minutos (juegos)',
        '800+ repair guides and content pages': 'Más de 800 guías de reparación y contenido',
        '5 games, XP rewards, daily streaks': '5 juegos, recompensas de XP, rachas diarias',
        'Quick answers': 'Respuestas rápidas',
        'Before you test,<br />know what to expect.': 'Antes de probar,<br />sabe qué esperar.',
        'Connect a controller, choose the signal you want to inspect, and get a result you can act on. The first test is always free.': 'Conecta un mando, elige la señal que quieres inspeccionar y obtén un resultado sobre el que puedas actuar. La primera prueba siempre es gratuita.',
        'Your controller deserves a real diagnosis.': 'Tu mando merece un diagnóstico real.',
        'Takes 2 minutes. No downloads, no accounts, no data collection.': 'Toma 2 minutos. Sin descargas, sin cuentas, sin recopilación de datos.',
        'Everything runs in your browser.': 'Todo funciona en tu navegador.',
        'Completely free': 'Completamente gratis',
        'No download required': 'No requiere descarga',
        'Works in 2 seconds': 'Funciona en 2 segundos'
    },
    'de': {
        'Controller Test Online | Free Gamepad Tester': 'Controller Test Online | Kostenloser Gamepad-Tester',
        'Run a free controller test online for PS5, PS4, Xbox, Switch, and PC. Use a gamepad tester to check drift, buttons, triggers, polling rate, and rumble.': 'Führe einen kostenlosen Controller-Test für PS5, PS4, Xbox, Switch und PC online durch. Nutze einen Gamepad-Tester, um Drift, Tasten, Trigger, Polling-Rate und Vibration zu prüfen.',
        'Controller test / precision diagnostics': 'Controller-Test / Präzisionsdiagnose',
        'Browser / ready': 'Browser / bereit',
        'Diagnose stick drift': 'Diagnostiziere Stick-Drift',
        'before you lose.': 'bevor du verlierst.',
        'Test your controller, mouse, and keyboard instantly. Catch drift, latency, and button failures before your warranty expires. Experience that you have never felt before.': 'Teste deinen Controller, deine Maus und deine Tastatur sofort. Erkenne Drift, Latenz und Tastenausfälle, bevor deine Garantie abläuft. Ein Erlebnis, das du noch nie gefühlt hast.',
        'Test your controller': 'Teste deinen Controller',
        'Check stick drift': 'Prüfe auf Stick-Drift',
        'hardware telemetry samples measured': 'gemessene Hardware-Telemetriedaten',
        'Works with': 'Funktioniert mit',
        'Live hardware telemetry': 'Live-Hardware-Telemetrie',
        'samples': 'Proben',
        'drift &amp; circularity measurements from real controller tests': 'Drift- &amp; Zirkularitätsmessungen aus echten Controllertests',
        '29 tools. One controller.': '29 Tools. Ein Controller.',
        '<br />Every test you need.': '<br />Jeder Test, den du brauchst.',
        'Flagship': 'Aushängeschild',
        'Controller Health Score': 'Controller Gesundheits-Score',
        'The only 0-100 score that measures drift, buttons, triggers, polling rate,': 'Der einzige 0-100-Score, der Drift, Tasten, Trigger, Polling-Rate',
        'and circularity in a single diagnostic. Get your grade: A+ to F.': 'und Zirkularität in einer einzigen Diagnose misst. Hole dir deine Note: A+ bis F.',
        'Get your score': 'Hol dir deinen Score',
        'View all 29 controller tests': 'Alle 29 Controller-Tests ansehen',
        'Mouse tests': 'Maus-Tests',
        'Keyboard tests': 'Tastatur-Tests',
        'Full-Setup Testing': 'Komplettes Setup-Testing',
        'Your mouse and keyboard get the same treatment.': 'Deine Maus und Tastatur bekommen dieselbe Behandlung.',
        'CPS speed, true DPI, 8K polling, click latency, double-click faults, scroll-wheel health —': 'CPS-Geschwindigkeit, echte DPI, 8K-Polling, Klick-Latenz, Doppelklick-Fehler, Scrollrad-Gesundheit —',
        '7 mouse tools. Plus a mechanical keyboard sandbox with NKRO matrix verification.': '7 Maus-Tools. Plus eine Sandbox für mechanische Tastaturen mit NKRO-Matrixüberprüfung.',
        'Keyboard Sandbox': 'Tastatur-Sandbox',
        'One platform.': 'Eine Plattform.',
        '<br />Every answer.': '<br />Jede Antwort.',
        'When your controller feels off, you currently visit 5-8 websites to': 'Wenn sich dein Controller seltsam anfühlt, besuchst du derzeit 5-8 Websites, um',
        'solve one problem. We own the entire journey in one place.': 'ein Problem zu lösen. Wir bieten die gesamte Reise an einem Ort.',
        'Start your journey': 'Beginne deine Reise',
        'Test your controller.': 'Teste deinen Controller.',
        '<br />Then play with it.': '<br />Dann spiele damit.',
        '5 browser games built around your controller inputs. Earn XP points,': '5 Browser-Spiele, die auf deine Controllereingaben abgestimmt sind. Sammle XP,',
        'level up, build a daily streak. No gaming site has this.': 'steige auf, baue eine tägliche Serie auf. Keine Gaming-Seite hat das.',
        'Precision games': 'Präzisionsspiele',
        'Reflex games': 'Reflexspiele',
        '2-Player games': '2-Spieler-Spiele',
        'Open Arcade': 'Arcade öffnen',
        'Earn while you play': 'Verdiene beim Spielen',
        'Test completion +50 pts': 'Test abgeschlossen +50 Pkt',
        'Achievements unlock': 'Erfolge freischalten',
        'Leaderboard rank': 'Bestenlisten-Rang',
        'Built different.<br />Not just another tester.': 'Anders gebaut.<br />Nicht nur ein weiterer Tester.',
        'Every competitor is a single-page app with 5-30 indexed pages and zero content.': 'Jeder Konkurrent ist eine One-Page-App mit 5-30 indizierten Seiten und null Inhalt.',
        'We are an 830+ page platform that owns the entire controller lifecycle.': 'Wir sind eine Plattform mit über 830 Seiten, die den gesamten Lebenszyklus des Controllers abdeckt.',
        'Other sites': 'Andere Seiten',
        '5-30 indexed pages (SPA)': '5-30 indizierte Seiten (SPA)',
        'Shows raw data, not answers': 'Zeigt Rohdaten, keine Antworten',
        '2-4 minute sessions': '2-4-minütige Sitzungen',
        'Zero repair guides or content': 'Keine Reparaturanleitungen oder Inhalte',
        'No games, no engagement loop': 'Keine Spiele, keine Motivation',
        '830+ indexed pages (Astro SSG)': 'Über 830 indizierte Seiten (Astro SSG)',
        'Diagnoses, fixes, and optimizes': 'Diagnostiziert, repariert und optimiert',
        '8-15 minute sessions (games)': '8-15-minütige Sitzungen (Spiele)',
        '800+ repair guides and content pages': 'Über 800 Reparaturanleitungen und Seiten',
        '5 games, XP rewards, daily streaks': '5 Spiele, XP-Belohnungen, tägliche Serien',
        'Quick answers': 'Schnelle Antworten',
        'Before you test,<br />know what to expect.': 'Bevor du testest,<br />weiß, was dich erwartet.',
        'Connect a controller, choose the signal you want to inspect, and get a result you can act on. The first test is always free.': 'Schließe einen Controller an, wähle das zu prüfende Signal und erhalte ein handlungsrelevantes Ergebnis. Der erste Test ist immer kostenlos.',
        'Your controller deserves a real diagnosis.': 'Dein Controller verdient eine echte Diagnose.',
        'Takes 2 minutes. No downloads, no accounts, no data collection.': 'Dauert 2 Minuten. Keine Downloads, keine Konten, keine Datenerfassung.',
        'Everything runs in your browser.': 'Alles läuft in deinem Browser.',
        'Completely free': 'Komplett kostenlos',
        'No download required': 'Kein Download erforderlich',
        'Works in 2 seconds': 'Funktioniert in 2 Sekunden'
    },
    'fr': {
        'Controller Test Online | Free Gamepad Tester': 'Test de Manette en Ligne | Testeur de Gamepad Gratuit',
        'Run a free controller test online for PS5, PS4, Xbox, Switch, and PC. Use a gamepad tester to check drift, buttons, triggers, polling rate, and rumble.': 'Faites un test gratuit de manette en ligne pour PS5, PS4, Xbox, Switch et PC. Utilisez un testeur pour vérifier le drift, les boutons, les gâchettes, le polling rate et les vibrations.',
        'Controller test / precision diagnostics': 'Test de manette / diagnostics de précision',
        'Browser / ready': 'Navigateur / prêt',
        'Diagnose stick drift': 'Diagnostiquez le stick drift',
        'before you lose.': 'avant de perdre.',
        'Test your controller, mouse, and keyboard instantly. Catch drift, latency, and button failures before your warranty expires. Experience that you have never felt before.': 'Testez votre manette, souris et clavier instantanément. Détectez le drift, la latence et les pannes de boutons avant l\'expiration de votre garantie. Une expérience inédite.',
        'Test your controller': 'Testez votre manette',
        'Check stick drift': 'Vérifiez le stick drift',
        'hardware telemetry samples measured': 'échantillons de télémétrie matérielle mesurés',
        'Works with': 'Fonctionne avec',
        'Live hardware telemetry': 'Télémétrie matérielle en direct',
        'samples': 'échantillons',
        'drift &amp; circularity measurements from real controller tests': 'mesures de drift &amp; de circularité à partir de tests réels',
        '29 tools. One controller.': '29 outils. Une manette.',
        '<br />Every test you need.': '<br />Tous les tests qu\'il vous faut.',
        'Flagship': 'Principal',
        'Controller Health Score': 'Score de Santé de Manette',
        'The only 0-100 score that measures drift, buttons, triggers, polling rate,': 'Le seul score de 0 à 100 qui mesure le drift, les boutons, les gâchettes, le polling rate',
        'and circularity in a single diagnostic. Get your grade: A+ to F.': 'et la circularité en un seul diagnostic. Obtenez votre note : de A+ à F.',
        'Get your score': 'Obtenez votre score',
        'View all 29 controller tests': 'Voir les 29 tests de manette',
        'Mouse tests': 'Tests de souris',
        'Keyboard tests': 'Tests de clavier',
        'Full-Setup Testing': 'Tests de Setup Complet',
        'Your mouse and keyboard get the same treatment.': 'Votre souris et votre clavier reçoivent le même traitement.',
        'CPS speed, true DPI, 8K polling, click latency, double-click faults, scroll-wheel health —': 'Vitesse CPS, vrai DPI, polling 8K, latence de clic, doubles clics, molette —',
        '7 mouse tools. Plus a mechanical keyboard sandbox with NKRO matrix verification.': '7 outils de souris. Plus un bac à sable de clavier avec matrice NKRO.',
        'Keyboard Sandbox': 'Bac à sable clavier',
        'One platform.': 'Une plateforme.',
        '<br />Every answer.': '<br />Toutes les réponses.',
        'When your controller feels off, you currently visit 5-8 websites to': 'Quand votre manette semble bizarre, vous visitez 5-8 sites web pour',
        'solve one problem. We own the entire journey in one place.': 'résoudre un problème. Nous gérons tout au même endroit.',
        'Start your journey': 'Commencez votre voyage',
        'Test your controller.': 'Testez votre manette.',
        '<br />Then play with it.': '<br />Puis jouez avec.',
        '5 browser games built around your controller inputs. Earn XP points,': '5 jeux de navigateur basés sur vos actions. Gagnez de l\'XP,',
        'level up, build a daily streak. No aucun autre site ne l\'a.': 'montez en niveau, créez une série. Aucun autre site ne l\'a.',
        'Precision games': 'Jeux de précision',
        'Reflex games': 'Jeux de réflexes',
        '2-Player games': 'Jeux à 2 joueurs',
        'Open Arcade': 'Ouvrir l\'Arcade',
        'Earn while you play': 'Gagnez en jouant',
        'Test completion +50 pts': 'Test terminé +50 pts',
        'Achievements unlock': 'Succès débloqués',
        'Leaderboard rank': 'Classement',
        'Built different.<br />Not just another tester.': 'Conçu différemment.<br />Pas juste un autre testeur.',
        'Every competitor is a single-page app with 5-30 indexed pages and zero content.': 'Chaque concurrent est une page avec 5-30 pages indexées et aucun contenu.',
        'We are an 830+ page platform that owns the entire controller lifecycle.': 'Nous sommes une plateforme de plus de 830 pages couvrant tout le cycle de vie.',
        'Other sites': 'Autres sites',
        '5-30 indexed pages (SPA)': '5-30 pages indexées (SPA)',
        'Shows raw data, not answers': 'Données brutes, pas de réponses',
        '2-4 minute sessions': 'Sessions de 2-4 minutes',
        'Zero repair guides or content': 'Aucun guide de réparation',
        'No games, no engagement loop': 'Pas de jeux, pas d\'engagement',
        '830+ indexed pages (Astro SSG)': 'Plus de 830 pages indexées',
        'Diagnoses, fixes, and optimizes': 'Diagnostique, répare et optimise',
        '8-15 minute sessions (games)': 'Sessions de 8-15 minutes (jeux)',
        '800+ repair guides and content pages': 'Plus de 800 guides de réparation',
        '5 games, XP rewards, daily streaks': '5 jeux, récompenses XP, séries quotidiennes',
        'Quick answers': 'Réponses rapides',
        'Before you test,<br />know what to expect.': 'Avant de tester,<br />sachez à quoi vous attendre.',
        'Connect a controller, choose the signal you want to inspect, and get a result you can act on. The first test is always free.': 'Connectez une manette, choisissez le signal et obtenez un résultat. Le premier test est gratuit.',
        'Your controller deserves a real diagnosis.': 'Votre manette mérite un vrai diagnostic.',
        'Takes 2 minutes. No downloads, no accounts, no data collection.': 'Prend 2 minutes. Sans téléchargement ni comptes ni suivi.',
        'Everything runs in your browser.': 'Tout s\'exécute dans votre navigateur.',
        'Completely free': 'Entièrement gratuit',
        'No download required': 'Aucun téléchargement requis',
        'Works in 2 seconds': 'Fonctionne en 2 secondes'
    },
    'ja': {
        'Controller Test Online | Free Gamepad Tester': 'コントローラーテスト オンライン | 無料ゲームパッドチェッカー',
        'Run a free controller test online for PS5, PS4, Xbox, Switch, and PC. Use a gamepad tester to check drift, buttons, triggers, polling rate, and rumble.': 'PS5、PS4、Xbox、Switch、PC用の無料コントローラーテストを実行。ドリフト、ボタン、トリガー、ポーリングレート、振動を確認します。',
        'Controller test / precision diagnostics': 'コントローラーテスト / 精密診断',
        'Browser / ready': 'ブラウザ / 準備完了',
        'Diagnose stick drift': 'スティックドリフトを診断',
        'before you lose.': '負ける前に。',
        'Test your controller, mouse, and keyboard instantly. Catch drift, latency, and button failures before your warranty expires. Experience that you have never felt before.': 'コントローラー、マウス、キーボードを瞬時にテスト。保証期間が切れる前にドリフト、レイテンシ、ボタンの故障を発見。これまで体験したことのない感覚を。',
        'Test your controller': 'コントローラーをテスト',
        'Check stick drift': 'ドリフトをチェック',
        'hardware telemetry samples measured': '件のハードウェアテレメトリ測定',
        'Works with': '対応デバイス',
        'Live hardware telemetry': 'ライブハードウェアテレメトリ',
        'samples': 'サンプル',
        'drift &amp; circularity measurements from real controller tests': '実際のコントローラーテストからのドリフト・円形度測定',
        '29 tools. One controller.': '29のツール。1つのコントローラー。',
        '<br />Every test you need.': '<br />必要なすべてのテスト。',
        'Flagship': 'フラッグシップ',
        'Controller Health Score': 'コントローラーヘルススコア',
        'The only 0-100 score that measures drift, buttons, triggers, polling rate,': 'ドリフト、ボタン、トリガー、ポーリングレート、',
        'and circularity in a single diagnostic. Get your grade: A+ to F.': '円形度を1回の診断で測定する唯一の0-100スコア。評価を確認（A+〜F）。',
        'Get your score': 'スコアを取得',
        'View all 29 controller tests': '全29のコントローラーテストを見る',
        'Mouse tests': 'マウステスト',
        'Keyboard tests': 'キーボードテスト',
        'Full-Setup Testing': 'フルセットアップテスト',
        'Your mouse and keyboard get the same treatment.': 'マウスとキーボードにも同じ待遇を。',
        'CPS speed, true DPI, 8K polling, click latency, double-click faults, scroll-wheel health —': 'CPS速度、真のDPI、8Kポーリング、クリックレイテンシ、ダブルクリックの不具合、ホイールの状態—',
        '7 mouse tools. Plus a mechanical keyboard sandbox with NKRO matrix verification.': '7つのマウスツール。さらにNKROマトリックス検証を備えたメカニカルキーボードサンドボックス。',
        'Keyboard Sandbox': 'キーボードサンドボックス',
        'One platform.': '1つのプラットフォーム。',
        '<br />Every answer.': '<br />すべての答え。',
        'When your controller feels off, you currently visit 5-8 websites to': 'コントローラーの調子が悪いとき、現在は5〜8つのサイトを訪れて',
        'solve one problem. We own the entire journey in one place.': '1つの問題を解決します。私たちは1つの場所ですべてを網羅しています。',
        'Start your journey': '旅を始める',
        'Test your controller.': 'コントローラーをテスト。',
        '<br />Then play with it.': '<br />そしてそれで遊ぶ。',
        '5 browser games built around your controller inputs. Earn XP points,': 'あなたの入力に基づいて作られた5つのブラウザゲーム。XPを獲得し、',
        'level up, build a daily streak. No gaming site has this.': 'レベルアップしてデイリーストリークを築きましょう。',
        'Precision games': '精度ゲーム',
        'Reflex games': '反射神経ゲーム',
        '2-Player games': '2プレイヤーゲーム',
        'Open Arcade': 'アーケードを開く',
        'Earn while you play': '遊びながら稼ぐ',
        'Test completion +50 pts': 'テスト完了 +50 pts',
        'Achievements unlock': '実績の解除',
        'Leaderboard rank': 'リーダーボードの順位',
        'Built different.<br />Not just another tester.': '他とは違う。<br />ただのテストツールじゃない。',
        'Every competitor is a single-page app with 5-30 indexed pages and zero content.': '競合他社は5-30ページのインデックス化されたページを持つSPAで中身がありません。',
        'We are an 830+ page platform that owns the entire controller lifecycle.': '私たちはコントローラーのライフサイクル全体を網羅する830以上のページを持つプラットフォームです。',
        'Other sites': '他のサイト',
        '5-30 indexed pages (SPA)': '5-30のインデックスページ (SPA)',
        'Shows raw data, not answers': '答えではなく生のデータを表示',
        '2-4 minute sessions': '2-4分のセッション',
        'Zero repair guides or content': '修理ガイドやコンテンツはゼロ',
        'No games, no engagement loop': 'ゲームなし、エンゲージメントなし',
        '830+ indexed pages (Astro SSG)': '830以上のインデックスページ (Astro SSG)',
        'Diagnoses, fixes, and optimizes': '診断、修理、最適化',
        '8-15 minute sessions (games)': '8-15分のセッション（ゲーム）',
        '800+ repair guides and content pages': '800以上の修理ガイドとコンテンツ',
        '5 games, XP rewards, daily streaks': '5つのゲーム、XP報酬、デイリーストリーク',
        'Quick answers': '簡単な回答',
        'Before you test,<br />know what to expect.': 'テストの前に、<br />期待できることを知る。',
        'Connect a controller, choose the signal you want to inspect, and get a result you can act on. The first test is always free.': 'コントローラーを接続し、調べたいシグナルを選択して、結果を取得します。最初のテストは無料です。',
        'Your controller deserves a real diagnosis.': 'あなたのコントローラーには本物の診断が必要です。',
        'Takes 2 minutes. No downloads, no accounts, no data collection.': '2分で完了。ダウンロード不要、アカウント不要、データ収集なし。',
        'Everything runs in your browser.': 'すべてがブラウザ上で実行されます。',
        'Completely free': '完全無料',
        'No download required': 'ダウンロード不要',
        'Works in 2 seconds': '2秒で動作'
    }
}

for lang in langs:
    new_content = content
    
    new_content = new_content.replace(
        "import { useTranslations } from '../../i18n/utils';",
        f"import {{ useTranslations }} from '../../i18n/utils';\nconst t = useTranslations('{lang}');"
    )

    for en, loc in translations[lang].items():
        new_content = new_content.replace(en, loc)
    
    os.makedirs(f"/Users/divyyadav/final_tool/controllertesting/src/pages/{lang}", exist_ok=True)
    with open(f"/Users/divyyadav/final_tool/controllertesting/src/pages/{lang}/index.astro", "w") as f:
        f.write(new_content)

print("Done generating localized pages.")
